### ISSUE TITLE
How to configure token of notify block in order that the kernelci token is invisible as well as the test result can be submitted to kernelci backend successfully?

### ISSUE THREAD

**Issue by jiewu9823** [kernelci/lava-docker#166]
Hi, I have some troubles need your help. I would be grateful if you can give any assistance.
I used lava-docker to deploy lava and used kernelci-docker to deploy kernelci. 
I need submit the test result of lava job to kernelci backend via notify block in lava job. The kernelci token was stored to Remote artifact tokens on the profile page and was named as kernelci-token. I configured token of notify block to kernelci-token and executed the lava job. The kernelci backend prompted “Token not authorized for IP address 210.120.168.110”.
How to configure token of notify block in order that the kernelci token is invisible as well as the test result can be submitted to kernelci backend successfully?

lava job notify block
````
notify:
  criteria:
    status: finished
  callbacks:
    - url: http://210.120.168.110:8081/callback/lava/test?lab_name=lab-01-nantong&status={STATUS}&status_string={STATUS_STRING}
      method: POST
      dataset: all
      token: kernelci-token
      content-type: json
````

kennelci response
````
[ WARNING/ Thread-26] Token not authorized for IP address 210.120.168.110
[ WARNING/MainThread] 403 POST /callback/lava/test?lab_name=lab-01-nantong&status=2&status_string=complete (180.120.167.208) 1.65ms
````
